---
- name: install tomcat server
  hosts: all
  become: yes

  tasks:
  - name: install java
    apt:
      name: java
      state: latest

  - name: download tomcat server packages
    get_url: 
       url: https://dlcdn.apache.org/tomcat/tomcat-10/v10.0.12/bin/apache-tomcat-10.0.12.tar.gz
       dest: /usr/local

  - name: unarchive tomcat package
    unarchive: 
        src: /usr/local/apache-tomcat-10.0.12.tar.gz
        dest: /usr/local
        remote_src: yes

  - name: start tomcat service
    shell: nohup /usr/local/apache-tomcat-10.0.12/bin/startup.sh
