---
- name: install tomcat server
  hosts: all
  become: yes
  vars_files:
      - tomcat_vars

  tasks:
  - name: install java
    apt:
      name: default-jdk
      state: latest

  - name: install jre
    apt:
      name: default-jre
      state: latest

  - name: download tomcat server packages
    get_url:
       url: "{{ tomcat_url }}"
       dest: /usr/local

  - name: unarchive tomcat package
    unarchive:
        src: /usr/local/{{ tomcat_package }}.tar.gz
        dest: /usr/local
        remote_src: yes

  - name: start tomcat service
    shell: nohup /usr/local/{{ tomcat_package }}/bin/startup.sh


